# Dockerfile pour la webapp Flask

FROM python:3.10-slim

# Définir le répertoire de travail à l'intérieur du conteneur
WORKDIR /webapp

# Copier le requirements.txt et installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
    
# Copier le reste du code (app.py, etc.)
COPY . .

# Indiquer le port exposé (8050 pour Flask)
EXPOSE 8050

# Démarrer l'application Flask
CMD ["python", "app.py"]
