version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27018:27017"   
    volumes:
      - mongo_data:/data/db

  scraper:
    build: .
    container_name: my_scraper
    depends_on:
      - mongo
    command: scrapy crawl nba_leaders

volumes:
  mongo_data:
