version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - nba_network

  scraper:
    build:
      context: .
    container_name: scraper
    depends_on:
      - mongodb
    networks:
      - nba_network

  web:
    build:
      context: .
    container_name: web
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - nba_network

networks:
  nba_network:
